// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc839.ReboundRumble.subsystems;

import org.usfirst.frc839.ReboundRumble.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Conveyor extends Subsystem 
{
    SpeedController conveyorVictor = RobotMap.conveyorconveyorVictor;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void Forward()
    {
        conveyorVictor.set( .5 );
    }
    
    public void Reverse()
    {
        conveyorVictor.set( -.5 );
    }
    
    public void Stop()
    {
        conveyorVictor.set( 0 );
    }
    
}
