// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc839.ReboundRumble.subsystems;

import org.usfirst.frc839.ReboundRumble.commands.DriveWithJoysticks;
import org.usfirst.frc839.ReboundRumble.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Drivetrain extends Subsystem 
{
    SpeedController leftDrivePodJaguar  = RobotMap.drivetrainleftDrivePodJaguar;
    SpeedController rightDrivePodJaguar = RobotMap.drivetrainrightDrivePodJaguar;
    RobotDrive      robotDrive          = RobotMap.drivetrainRobotDrive;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        setDefaultCommand(new DriveWithJoysticks());
    }
    
    public void setDriveSpeeds( double dLeft, double dRight )
    {
        robotDrive.tankDrive( dLeft, dRight );
    }
    
    public void stop()
    {
        robotDrive.drive( 0, 0 );
    }
    
}
