// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc839.ReboundRumble.subsystems;

import org.usfirst.frc839.ReboundRumble.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc839.ReboundRumble.commands.ShooterCmd;

/**
 *
 */
public class Shooter extends Subsystem 
{
    SpeedController shooterJaguar = RobotMap.shootershooterJaguar;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        // Set the default command for a subsystem here.
        setDefaultCommand(new ShooterCmd());
    }
    
    public void Forward()
    {
        shooterJaguar.set( 1 );
    }
    
    public void Reverse()
    {
        shooterJaguar.set( -1 );
    }
    
    public void Stop()
    {
        shooterJaguar.set( 0 );
    }
    
}
